### ISSUE TITLE
Update Dask landing page?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3174]
We may want to replace the current main page of the dask documentation with a landing page that is friendlier for first-time visitors.

Our current documentation at https://dask.pydata.org presents a first-time reader with a linear stream of text to read.  Contrasting this with Scikit-Learn's front-page, http://scikit-learn.org/stable/, which presents the reader with a high-level description in four bullet points, followed by a grid of options for regression, classification, etc, with applications and example algorithms for each.  I think that this quick split to an application area might suit Dask as well with categories like the following (alternatives welcome):

1.  dataframes
2.  arrays
3.  machine learning
4.  custom algorithms (delayed)
5.  real-time (futures)
6.  deployment 

Additionally, if we're able to break out of the standard sphinx layout for this page we can probably use horizontal screen space more effectively.  There are some challenges to this though; we probably want to maintain the use of vanilla read-the-docs.  Presumably there is a nice way to deviate a bit here, I'm not familiar with it though.

cc @electronwill @TomAugspurger who I suspect are more experienced here than I am

**Comment by mrocklin** [comment]
I was considering using just straight HTML+CSS with some Flexbox system.  To be clear, I don't mind dropping sphinx here and going to straight HTML.   I do mind introducing a build or upload steps in our docs deployment (which is currently trivial).

**Comment by electronwill** [comment]
That also works.

RST files can include sections of raw HTML: https://docs.anaconda.com/restructuredtext/detailed#youtube-videos-and-other-raw-html-in-rst-files

**Comment by mrocklin** [comment]
Yeah, and this is how sklearn does it.  I suspect that we would still have to get away from the template though, which adds a bunch of stuff that may not be appropriate, and also limits our horizontal space.

**Comment by jakirkham** [comment]
Admittedly these are just my thoughts. So feel free to disagree.

Maybe we could add an org webpage repo and make that the landing page. At least some of the points up there (e.g. machine learning and deployment) are actually totally different projects/repos. Not to mention this would avoid having the docs in Dask serve two totally different purposes namely a landing page and docs with Sphinx. Expect separating them will avoid unnecessarily constraining our choices about what makes sense for these two different concerns.

Side note: This could also be a good opportunity to think about whether the blog should be included the webpage and/or the org.

**Comment by mrocklin** [comment]
I agree that a separate page might be nice.  I also agree that this could
be a good place to advertise a blog, if one were to appear.  Where would we
host this?

**Comment by mrocklin** [comment]
And at what domain?

**Comment by mrocklin** [comment]
It looks like dask.org redirects to anaconda.org, so my guess is that
Anaconda Inc. owns that domain, which might suffice.

**Comment by jakirkham** [comment]
Have no strong feelings on which domain. Both options you mentioned sound good.

I think we used Cloudflare at conda-forge and believe matplotlib does too. Don't know too many details (Phil set it up), but this [blog post]( https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/ ) might help.

**Comment by mrocklin** [comment]
I'm fooling around a bit with this this weekend:

http://matthewrocklin.com/dask-website/

**Comment by mrocklin** [comment]
OK, so a summary of what we have:

1.  a static HTML page that has the following organization
    -  APIs
        - arrays
        - dataframes
        - machine learning
        - custom
    - high level motivating reasons to choose dask
    - getting started
        - install
        - deploy
        - learn more

### CSS Framework

I'm using [bulma](https://bulma.io/) for css, mostly because I've used it before for a few of the scheduler pages.  The original reasons I chose bulma was that it struck a decent balance between being easy to use and feature-full while also lightweight

### TODOs

The following are things that I'd like to see done.  Now would be a good time to check in with people to make sure that people are comfortable with this direction.

- [ ] Add tabs to the API tiles similar to how we have them for install and deploy options on the bottom.  This would allow us to include motivating code examples and images for each of a few applications.  For example for arrays we might have netcdf data, images, and convex optimization algorithms
- [ ] Change coloration to the Dask orange, throw some logos around, etc.
- [ ] Improve the dask.pydata.org array/dataframe/delayed pages to serve as better landing sites.  Currently the bare array/dataframe/delayed pages are mostly TOC pages.
- [ ] Do more visual design (mostly getting feedback from others) on titles, banners, etc..

**Comment by jakirkham** [comment]
Looks pretty good. Have some minor layout points and a question below, but it seems reasonable to table the layout points until we are sure everyone likes the content.

The layout of the machine learning section looks like it could use some tweaking (graph appears outside the border). Could do some tweaking with the Dataframe diagram (e.g. extending Dask curly brace, maybe flip sides of the two curly braces and bring text into blocks). Might want to increase the spacing between the Dask Array diagram and text. Though this sort of stuff is always pretty tricky to get right and may not make sense to do until everyone is settled on the content.

What were you thinking of for the "Custom" section?

<img width="1552" alt="screen shot 2018-02-18 at 19 37 23" src="https://user-images.githubusercontent.com/3019665/36358904-2f1726ca-14e3-11e8-9cc9-b94cd60e7fe3.png">

**Comment by mrocklin** [comment]
For custom I'm thinking dask.delayed and concurrent.futures. 

I agree about the layout issues.  These are resolvable.

**Comment by mrocklin** [comment]
Stack overflow question about embedding a standalone HTML page into a sphinx site: https://stackoverflow.com/questions/48889270/include-standalone-html-page-in-sphinx-document

**Comment by jacobtomlinson** [comment]
Just to add my two cents, you need a task graph somewhere on the page, perhaps even as a background image. One of the things that made dask really click for us was seeing some awesome task graphs in your [blog posts](http://matthewrocklin.com/blog/work/2017/01/24/dask-custom).

As for blog posts I've had good success in a [side project of mine](https://opsdroid.github.io/) using Medium (insert alternative low maintenance blogging service here) and then a little snippet of JavaScript on the website to pull the RSS feed from Medium and display the latest post titles.

**Comment by jcrist** [comment]
I just tried tweaking the sphinx `conf.py` to rename `index.html` to something else (`docs.html`), and everything works fine. Could include a raw `index.html` file then to override the landing page, and redirect to `docs.html` for the sphinx docs?

**Comment by mrocklin** [comment]
Will sphinx / readthedocs pick up a raw html file by default or do we need to register it somewhere?

I've also been looking at the [Bokeh docs](https://bokeh.pydata.org/en/latest/) as a nice example of custom HTML integrated into a sphinx site.

**Comment by jcrist** [comment]
> Will sphinx / readthedocs pick up a raw html file by default or do we need to register it somewhere?

This seems to work: http://www.sphinx-doc.org/en/master/config.html#confval-html_extra_path

Full conf.py diff:

```diff
diff --git a/docs/source/conf.py b/docs/source/conf.py
index 7271348..aa8ce9d 100644
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -40,7 +40,8 @@ source_suffix = '.rst'
 #source_encoding = 'utf-8-sig'
 
 # The master toctree document.
-master_doc = 'index'
+master_doc = 'docs'
+html_extra_path = ['index.html']
 
 # General information about the project.
 project = u'dask'
@@ -193,7 +194,7 @@ latex_elements = {
 # Grouping the document tree into LaTeX files. List of tuples
 # (source start file, target name, title, author, documentclass [howto/manual]).
 latex_documents = [
-  ('index', 'dask.tex', u'dask Documentation',
+  ('docs', 'dask.tex', u'dask Documentation',
    u'Dask Development Team', 'manual'),
 ]
 
@@ -223,7 +224,7 @@ latex_documents = [
 # One entry per manual page. List of tuples
 # (source start file, name, description, authors, manual section).
 man_pages = [
-    ('index', 'dask', u'dask Documentation',
+    ('docs', 'dask', u'dask Documentation',
      [u'Dask Development Team'], 1)
 ]
 
@@ -237,7 +238,7 @@ man_pages = [
 # (source start file, target name, title, author,
 #  dir menu entry, description, category)
 texinfo_documents = [
-  ('index', 'dask', u'dask Documentation',
+  ('docs', 'dask', u'dask Documentation',
    u'Dask Development Team', 'dask', 'One line description of project.',
    'Miscellaneous'),
 ]
```

**Comment by jcrist** [comment]
Alternatively, people seem to like [doctr](https://github.com/drdoctr/doctr) for deploying more custom project websites/docs to github pages. I see no reason to leave readthedocs, just throwing out another option.

**Comment by mrocklin** [comment]
I've updated http://matthewrocklin.com/dask-website/ to have tabs for the array section for different applications.  I like the immediate appeal to use cases, however I also feel like I'm starting to cram a lot of content into a small space.  I'm not sure it's best to keep things here on the front page where they are immediately discoverable or back out to other pages.

The standalone HTML page is also getting a bit dense with the tabs.  I'm comfortable editing like this but it introduces barriers to entry for others to update the content here in the future.  There is a potential tradeoff here to switch to some templating system to generate the HTML.  This adds complexity into the doc setup (we would presumably roll this into the makefile and make before commit).

**Comment by mrocklin** [comment]
OK, I've simplified the amount of content in each box and added tabs everywhere.  Feedback appreciated.

**Comment by TomAugspurger** [comment]
I reached out to a former coworker who is a web designer. She’s busy this week but may have a chance to glance over this next week.

________________________________

**Comment by mrocklin** [comment]
I could use help here in the following ways:

1.  High level feedback.  Is this the approach we want to take?  What are some big changes that we might want to make?
2.  Content and images.  I've put down some general content to set a pattern, but I would welcome changes to language (being mindful of concision constraints) and informative images.

**Comment by martindurant** [comment]
Quick thoughts:

- Layout is nice; probably still needs a lead paragraph of what dask is
- No particular place to put the basic information now top of http://dask.pydata.org/en/latest/index.html (pydata ecosystem, graph, cluster scaling)

Specific issues:

- rather wide, does not fill well on my screen without zooming out
- tabs in each quadrant do not highlight
- top quadrants should be same height
- graphic under "numerical algorithms" same as all of the machine learning graphics
- code under "numerical algorithms" got ugly horizontal scroll bar
- in dataframe/data-access, read_csv refers to parquet path
- tabs should not all have the same link (e.g., asynchronous should link to futures, not delayed)

**Comment by TomAugspurger** [comment]
## Content

- "Open source" isn't mentioned anywhere on the landing page (though the "Source" dropdown strong hints that it's open source)
- Add dask-ml docs to the Documentation dropdown?
- Leverage powerful upstream libraries
- Youtube Channel links to a specific talk. Should we make a dask playlist and link to that?
- The text sections "Dask Started with NumPy", "Dask Grew...", "Today" under the "Why use Dask?" feels out of place. I think since they're wordier, and maybe too detailed for a "Why use dask" section. What was your reason for including them there? I think just a bit of text saying that dask is used by many groups and libraries would be more effective.

## Visual

- A visual indicator of which tab is currently selected 
![screen shot 2018-02-21 at 3 21 26 pm](https://user-images.githubusercontent.com/1312546/36506015-f534c0e0-171a-11e8-891c-422ed7690b9a.png).
The one you get with `on:hover` (maybe with a different color) seems good
![screen shot 2018-02-21 at 3 22 06 pm](https://user-images.githubusercontent.com/1312546/36506048-0ca5712a-171b-11e8-9bc8-5b254759b402.png)
- verticle align the dask logo (and probably the bullets)
![screen shot 2018-02-21 at 3 25 10 pm](https://user-images.githubusercontent.com/1312546/36506184-703f8626-171b-11e8-8772-54af1b79e1bf.png)
- Make each tab without a cell the same height? It's visually distracting to see other tabs cells jump around when you change a tab. This will require us to settle on the content of course.
- Add a thin border to the bottom of the navbar that's the same as the background green 
![screen shot 2018-02-21 at 3 29 04 pm](https://user-images.githubusercontent.com/1312546/36506370-0dddb8f8-171c-11e8-814a-a6ebfa8c59c0.png)
- Would be nice to syntax highlight all the code examples (`pygmentize -f html` should do the job) if we include the right bits in the CSS

Mobile / small screens

- The hamburger button doesn't work when the window is collapsed
- The 2x2 layout should collapse to 4x1 sooner, else you're in a state like 
![screen shot 2018-02-21 at 3 20 32 pm](https://user-images.githubusercontent.com/1312546/36505974-d382616e-171a-11e8-9be1-8dc0b75f2683.png)

I'll think more about what can go in the tabs later. Overall 👍

**Comment by mrocklin** [comment]
I agree with all of these comments from both @martindurant and
@TomAugspurger.  Unfortunately for many of them I don't yet know how to
resolve them quickly within the framework that I'm currently using.

**Comment by mrocklin** [comment]
I think in general comments about styling and layout are welcome, but less
valuable now than additional comments, good selection of images, etc..

**Comment by mrocklin** [comment]
> Layout is nice; probably still needs a lead paragraph of what dask is

@martindurant any desire to give this a shot?

**Comment by mrocklin** [comment]
I've fixed many of the layout issues.

1.  columns collapse more cleanly on reduced sized windows
2.  I've pinned specific heights in the boxes for now (though this feels like I'm throwing too much style into the HTML)
3.  The hamburger now works on mobile, but remains quite small.

**Comment by jcrist** [comment]
Apologies for the late review here. Overall I like the slimmed down content, but the page layout feels too busy to me.

- The 2x2 grid is rather wide, and makes reading the bullets in each one harder. Not enough whitespace between/around content. I'm also not sold on the fancy widgets.
- The "Dask Started with numpy..." content feels out of place, and may make more sense in a history page in the docs, or somewhere else more-prosey. I think I'd drop it completely from the landing page.
- The "getting started" content is nice in theory, but due to particularities about different systems (e.g. yarn) may be insufficient. I might switch this out for just "how to install and run locally", and a link/links for setting up on various clusters.

In terms of content for the main page, I think the following is important:
- Sparsity. Don't need tons of details, just a set of bullet points on what dask is and why you might use it.
- Subcategories (array, dataframe, etc...) with *minimal* description and links to the corresponding docs section
- Link to the relevant github pages for issues/prs.
- Links to related ecosystem projects (probably not on the landing page, but there should be a link to this content somewhere prominent).
- Maybe a *small* newsfeed showing recent release dates, blogposts, etc...

This may be the first contact a user has with the project. We don't need to tell them everything at once, just an elevator pitch about why you might want to use dask. I'd rather err on the side of too little content on the landing page than too much.

A few examples of project landing pages I like:
- https://spark.apache.org/. I really like how they've consolidated the selling points into 4 bullets. Makes good use of whitespace, links to more details on specific topics if I want them.
- http://scikit-learn.org/stable/. Minimal, no fancy web components, just a high level overview and links to subsections in the docs. Newsfeed at the bottom notes recent release dates, etc...
- http://jupyter.org/. A bit more than I'd put on the landing page, but the important stuff is all towards the top. Persistent dropdown keeps the relevant links handy.
- https://www.djangoproject.com/

Of course this is all opinion based, just my 2 cents.

**Comment by mrocklin** [comment]
Thank you for the high-level feedback @jcrist, this is exactly what I was looking for.  

> The "Dask Started with numpy..." content feels out of place

Happy to remove the history bits.  This has come up a few times now.

> This may be the first contact a user has with the project. We don't need to tell them everything at once, just an elevator pitch about why you might want to use dask. I'd rather err on the side of too little content on the landing page than too much.

I usually agree strongly with the sparsity argument.  Let me try to motivate my approach here.  When I talk to people they often have a particular application in mind.  When I give them the high level overview their eyes sort of gloss over.  Eventually we hit upon the central thing in their mind "Oh, so dask lets me make my own machine learning algorithms, why didn't you just say that first?" "Oh, so dask scales pandas, why didn't you just say that first?" "...".  It's somewhat difficult to find that thing for them.  

I think that we serve a few different communities that perceive technology space differently.  There is some value in allowing readers to quickly find that Dask serves their community.  My first approach to this was to have tabs with applications like "earth science", "web servers", "scikit-learn" arranged in tabs in the landing page.  However, maybe there are nicer ways to accomplish this that are less busy at first glance but still allow for drilling down.  One obvious way would be to redirect to another page.  There might also be a way to rearrange the tabs here.

**Comment by jcrist** [comment]
>  However, maybe there are nicer ways to accomplish this that are less busy at first glance but still allow for drilling down. One obvious way would be to redirect to another page. 

I like the idea of redirecting to a specific page. Perhaps reorganize the 4 boxes into vertical bullets. Something like:

- Parallel Arrays
- Parallel Dataframes
- Machine Learning
- Custom Workflows

each with 1-2 sentences describing them, maybe an image, and a link to a relevant sub-page (either docs or more specific high-level content).

**Comment by mrocklin** [comment]
I think I want to push that classes of example applications (like
biomedical imaging, numerical algorithms, etc..) are visible, perhaps just
as links but ideally more prominently, from the first viewing of the
landing page.  I believe that these are more engaging for the kinds of
people for whom landing pages are useful, than just terms like arrays,
dataframes, and machine learning alone.

**Comment by mrocklin** [comment]
I also *do* think that there is value to having them accessible in a way
that doesn't visibly require navigating away to another page, if there is a
way to make that align with our other goals of sparsity.

**Comment by jcrist** [comment]
> I think I want to push that classes of example applications (like biomedical imaging, numerical algorithms, etc..) are visible, perhaps just as links but ideally more prominently, from the first viewing of the landing page.

Since the people using dask directly are likely to be developers, I'd think a bullet titled "Parallel Arrays" with example usecases like "biomedical imaging" or "numerical algorithms" underneath in the short prose description of it would be equally valid.

If I went to the dask landing page and saw in big font "Earth Science" I'd think "Dask is for earth science", not "dask can be used for earth science". While there is value in showing which communities we interact with and have been useful for, you also run the risk of shoehorning yourself into those applications alone. I suspect developers understand "Parallel big arrays" well enough that they can imagine how this might be useful to them without requiring a high-level bullet just for their field.

**Comment by mrocklin** [comment]
> Since the people using dask directly are likely to be developers

Ah, this may be the point of our disagreement.  I'm not writing this landing page for developers, I'm writing it for people around developers who make decisions about what technologies to adopt.  I suspect that most of the pages that you point to above were similarly not written for developers.  There is always a separate developer docs section, much like what we have at dask.pydata.org.  

Consider the scikit-learn page (which I think is among the strongest there) you quickly have a small menu of things to consider like Clustering, and then diving more deeply you get to K-Means.  This directs a user towards their interests quickly.  I think that most people who see that page understand that Scikit-Learn has more clustering algorithms than just K-means and spectral.  I think it's ok to list a few example cases.

> If I went to the dask landing page and saw in big font "Earth Science" I'd think "Dask is for earth science", not "dask can be used for earth science"

I entirely agree, and so we shouldn't have this be anywhere near front-and-center.  I agree that this would be a bad move.  However I think it's safe to list it as one application among many, and only after you've seen that dask provides general purpose parallel arrays.  

As another, somewhat orthogonal example, lets look at Bokeh's landing page: https://bokeh.pydata.org/en/latest/

![image](https://user-images.githubusercontent.com/306380/36564685-1f10ecdc-17ec-11e8-99d4-9ececae6f259.png)

Being a plotting library they have a nice opportunity here.  They immediately present the user with a gallery of plots.  People going to this page quickly identify with one of these images, click, and are drawn in.  I think that this gallery is much more compelling than any of the text above it.

I don't think that most people looking to adopt technology say "I need a big dataframe" or "I need a big array".  I think it is more likely for them to say "I need to analyze all of these images" or "I need to handle these futures contracts".  I believe that as developers we are more biased towards tools while users tend to be more biased towards applications.

**Comment by mrocklin** [comment]
To be clear I'm not saying "lets keep things the way they are at the current proposed state" I'm saying the following "I'm coming into this with some constraints and here's why I think they're important.  I hear your constraints as well and I agree with them.  I think that there is probably a better design that satisfies all constraints."

**Comment by mrocklin** [comment]
Coming back to this, what should a Dask landing page look like?  If anyone has time to put together a mock up or content that they would like to see I think that this would be valuable for the project.

**Comment by mrocklin** [comment]
Here is another very rough take: http://matthewrocklin.com/dask-webpage/

I mostly stole styling from a couple bootstrap examples and added some generic content.  There is plenty to do (colors, images, links, etc.) at this point I'm looking for high level thoughts.

**Comment by jcrist** [comment]
High level review:

- I like this approach. This hits the main selling points quickly and directly, without being overly verbose.

- I like the institutions using and supporting section, but wonder if we should/need to ask these institutions if it's ok to use their name here.

- The headers "numpy", "pandas", and "machine-learning" feel a bit off, since the first two are libraries and the third is a field. Perhaps "numpy, pandas, scikit-learn", or "arrays, dataframes, machine-learning". No strong thoughts - either way, I like the breakdown.

What are your thoughts on links in the top-bar? I think they should be:
- "Why dask?" (link to the new why dask docs page)
- "Documentation" (link to the main docs page)
- "Installation" (link to install instructions, which may have sublinks to cluster setup guides, etc...)
- "Github link" (maybe the org, or just dask/dask? I often want to see the github page quickly after viewing the landing page). Alternatively, could have a link to "development"/"getting involved" or something similar, that links to our developer docs, which then link to github.

For the "view details" links under numpy, etc... are you planning on linking directly to the docs for those sub-modules? That seems fair to me, just curious.

Anyway, overall I think this is a good approach. Elevator pitch, with just enough detail and links to delve further.

**Comment by mrocklin** [comment]
Thanks for the feedback @jcrist .   I really appreciate it and generally agree with your comments.  Does anyone else have the time to weigh in here?

**Comment by mrocklin** [comment]
Also, I think that it would be useful to have a version of this image that had a transparent background for the header

![](http://matthewrocklin.com/slides/images/grid_search_schedule.gif)

Ideally it would also be high-res while also small in size (not sure how possible this is for a gif).  Anyone have any ideas?

**Comment by martindurant** [comment]
The page does indeed look a lot more like the current going style for data landing pages.

Actually, I think it's a shame to loose the tabs, as a kind of pictorial fast TOC: fast access to large number of pages into the docs (minimising the number of clicks to get somewhere specific) without leaving the front.

I agree with Jim's point: I would go for arrays/dataframes/ML. The equivalent of delayed/submit is very much an afterthought and last thing mentioned, most people don't read that far.

**Comment by mrocklin** [comment]
The larger elements at the bottom like "Familiar for Python Users" are probably large enough for tabs if we wanted them.  That would probably mean that arrays, dataframes, ML, and delayed/futures would take those sections while the virtues like familiar, scales, flexible would move up top to where arrays/dataframes/ML is now.  

Last time @jcrist voiced some concern about the use of tabs.  Does that concern carry over to this layout as well?

**Comment by TomAugspurger** [comment]
I prefer the version without tabs. As a compromise, the contents previously within the tabs could be included in http://dask.pydata.org/en/latest/array.html and others, expanding the "Common uses" section. Or they could be included further down on the landing page. The "View details" links would take you there.

I think the only piece of content that *may* be missing is delayed / custom algorithms, to emphasize that dask is "not just map reduce". I say "may",  because that's likely of secondary importance at this stage, and it's included further down.

**Comment by mrocklin** [comment]
Can you state a bit more about your reasoning for wanting to avoid tabs?  

I think that my motivation for them is that I want users to be able to explore use cases a bit without navigating away.  Can you express your motivations a bit for why the tabs in the previous implementation  seemed off?  Do you have any thoughts about how to provide some content about use cases in a clean way, or would you prefer to avoid this altogether?  If so, then can you explain why?

**Comment by mrocklin** [comment]
I've updated style and content a bit.  http://matthewrocklin.com/dask-webpage/

**Comment by mrocklin** [comment]
> I like the institutions using and supporting section, but wonder if we should/need to ask these institutions if it's ok to use their name here.

I'm also curious about this.  Does anyone know what is standard here?  Do we know someone who would know?

**Comment by mrocklin** [comment]
I've raised a PR here: https://github.com/dask/dask/pull/3315

**Comment by jakirkham** [comment]
Wow! I really like how this page is organized. 😄

Have some comments, but I'll save them for the PR.
