### ISSUE TITLE
NEP-18 Issue Tracking

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4731]
We want to track what are the issues that need to be solved in the long-term for NEP-18 support and interoperability with libraries such as CuPy.

Structural changes:
- [ ] Support `dask.Array._meta` attribute https://github.com/dask/dask/pull/4543 #4888 
- [ ] `__array_function__` fallback to NumPy implementation https://github.com/numpy/numpy/issues/12974, https://github.com/numpy/numpy/pull/13305

Functional changes:
- [x] Support for `shape=` on `*_like functions
  - [x] NumPy https://github.com/numpy/numpy/pull/13046
  - [x] CuPy https://github.com/cupy/cupy/pull/2171
  - [x] Dask https://github.com/dask/dask/issues/4875
- [x] Special empty slice copying in https://github.com/cupy/cupy/pull/2079, requires environment variable `CUPY_EXPERIMENTAL_SLICE_COPY=1`
- [x] Support for `__array_function__` on Dask https://github.com/dask/dask/issues/4563

Bug fixes:
- [x] `da.einsum` doesn't work with CuPy arrays #4898 
- [x] `diag()` fails on CuPy arrays https://github.com/dask/dask/issues/4490
- [x] prevent `fix()` depending on CuPy's `__array_wrap__` https://github.com/dask/dask/issues/4496
- [x] Dispatch modules with `__array_function__` https://github.com/cupy/cupy/issues/2011
- [x] Multi-threaded support for CuPy on CUDA libraries requiring handles https://github.com/dask/dask/issues/4487, https://github.com/cupy/cupy/issues/2045
- [x] `mean()`/`moment()` reduction issues https://github.com/dask/dask/issues/4481, https://github.com/dask/dask/issues/4523
- [x] `flatnonzero()` requires `compress()` which is not implemented in CuPy https://github.com/dask/dask/issues/4497
- [x] Infinite recursion on CuPy `isclose()` https://github.com/cupy/cupy/issues/2029
- [x] `da.pad` support: https://github.com/dask/dask/issues/6117
- [x] `da.fft` support: https://github.com/dask/dask/issues/6118

Testing:
- [ ] Increase `__array_function__` testing https://github.com/dask/dask/pull/4486

**Comment by mrocklin** [comment]
Thanks @pentschev !  This is great.  I enjoyed looking through the various NumPy and CuPy PRs and issues listed here.

**Comment by jakirkham** [comment]
I checked some boxed here based on things that appear to already be completed (merged PRs, closed issues). Hope that is ok 🙂

**Comment by quasiben** [comment]
@pentschev do you think this issue can be closed now ?

**Comment by pentschev** [comment]
I think so, we've covered the vast majority of things that we thought were relevant at time of writing. We are unlikely to resolve the last few remaining points as most of the common use cases are now covered in Dask, therefore closing it seems ok.
