### ISSUE TITLE
Array._meta missing functionality tracker

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4888]
Here we track `Array._meta` functionality that did not get in with #4543, but should still be implemented.

- [ ] Pass `meta` to all `Array()` constructors where `dtype` does not suffice
  - [ ] `dask/array/core.py` (incomplete, must include fix for #4929)
  - [ ] `dask/array/creation.py` (must include fixes for #4841, #4842)
  - [ ] `dask/array/percentile.py`
  - [ ] `dask/array/reductions.py` (incomplete)
  - [ ] `dask/array/routines.py` (incomplete)
  - [ ] `dask/array/slicing.py`
  - [ ] `dask/array/wrap.py`
  - [ ] `dask/array/tests/test_array_core.py`
  - [ ] `dask/array/tests/test_atop.py`
  - [ ] `dask/array/tests/test_percentiles.py`
  - [ ] `dask/array/tests/test_slicing.py`
  - [ ] `dask/dataframe/core.py`
  - [ ] `dask/dataframe/io/tests/test_io.py`
  - [ ] `docs/source/array-design.rst` (update docs)

- [ ] Eventually move all NumPy-specific array creation to match in use array type (discussion in #4883, initial implementation of NEP-35 in #6738 )
  - [ ] `np.empty`, `np.full`, `np.ones`, `np.zeros`
  - [ ] `np.array`
  - [ ] `np.asarray`
  - [ ] Others?

**Comment by jakirkham** [comment]
Would add `stack` to this list. Have also added it separately as issue ( https://github.com/dask/dask/issues/4929 ).

**Comment by pentschev** [comment]
Thanks for the report @jakirkham. On the list I have on top I'm keeping the files that still need to be fixed one-by-one, which means they can have one or multiple functions. Specifically `stack` is part of `dask/array/core.py`. I'll link the issue, but I'm intentionally not listing every function there, otherwise that list will become huge.

**Comment by pentschev** [comment]
I'm not trying to discourage opening issues for specific functions that may require higher priority, it's great to know which ones are more important!

**Comment by jakirkham** [comment]
Yep, agree it's not worth listing them all.

In general `stack`, `concatenate`, and `block` are of importance because they can be useful for [building a cohesive Dask Array from pieces]( https://docs.dask.org/en/latest/array-stack.html ). `concatenate` already uses `_meta` and `block` uses `concatenate` internally. So `stack` is the only one of these 3, which is not covered.

**Comment by pentschev** [comment]
I wasn't aware of that, and honestly, this is a very good point. I guess we should prioritize those. So far, my priority has been somewhat arbitrary:

1. Functions with open issues and those that I was directly using;
1. Functions that were quick and easy to fix;
1. Alphabetical order.

**Comment by jakirkham** [comment]
That seems like a reasonable way to set priorities. Given this scheme, is opening issues like I've done a reasonable way to alert you to important things or is there a different way you'd prefer to manage this?

**Comment by pentschev** [comment]
I think it's good to open issues in two cases:

1. They need priority;
1. The function in question is not listed on this issues' description or mistakenly marked as done.

The only thing I want to prevent is that we end up with one issue for each function that doesn't yet support `_meta`, because that defeats the purpose of the issue here.

Also, if you create a new issue for one of the reasons I cited above, please make sure to add a comment here so we don't miss it.

**Comment by benbovy** [comment]
I created #5353 for `Array.persist()` .

**Comment by pentschev** [comment]
As we covered most of the common use cases in Dask, we're unlikely to move the needle in this tracker, mostly doing some work in the eventuality of users needing support for specific functions. Therefore I'm closing it.
