### ISSUE TITLE
Regressions from fsspec dependency

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#5330]
Collecting a list of regressions thought to be related to the fsspec migration

- [x] s3 read from server not providing size https://github.com/dask/dask/issues/5222 / https://github.com/dask/dask/issues/5310 
- [x] HDFS ls https://github.com/dask/dask/issues/5285
- [x] follow symlinks: https://github.com/dask/dask/issues/5233
- [x] Don't request past range https://github.com/dask/dask/issues/5186
- [x] making directory: https://github.com/dask/dask/issues/5210
- [x] pyarrow and fsspec: https://github.com/intake/filesystem_spec/issues/104
- [ ] Random permission errors: https://github.com/dask/s3fs/issues/218
- [x] fsspec webhdfs authentication https://github.com/dask/dask/issues/5257
- [x] duplicate reads for small files https://github.com/intake/filesystem_spec/issues/110
- [x] duplicate reads again https://github.com/dask/dask/issues/5336
- [x] Bump minimum versions: https://github.com/dask/dask/issues/5298. Partly addressed in https://github.com/intake/filesystem_spec/pull/120. Fully addressing would may require compat shims in `dask.bytes`. Need to check)
 
I'm looking into the remaining issues.

**Comment by mrocklin** [comment]
cc @birdsarah

**Comment by martindurant** [comment]
I think we can close this now, since the only remaining thing is the permissions. https://github.com/dask/dask/issues/5361 is probably the right place to discuss commit/rollback of entire data-output operations.
