### ISSUE TITLE
Identify performance opportunities from recent benchmark

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#6264]
This article seems decently well done.  It has a nice notebook at the end that includes simple workflows that apparently Dask Dataframe didn't perform very well on.  I think that it would be a useful exercise for someone to go through it, produce performance reports for each section and present them here for analysis.  I suspect that we could find some opportunities for performance optimization.

https://towardsdatascience.com/beyond-pandas-spark-dask-vaex-and-other-big-data-technologies-battling-head-to-head-a453a1f8cc13

## Edit: lessons learned

- [x]  make len(df) be len(df.index), and that this actually triggers the existing columns optimization for parquet (https://github.com/dask/dask/pull/6355)
- [ ] specifically for len(df) from parquet, use metadata nrows value rather than loading (#6387)
- [ ] combine column selections and also pass down to parquet (and csv or others!) (#6388)
- [x] gather_statistics in read_parquet: revisit when this is triggered at all, and quit early if failing, preventing the load of metadata even if gather_statistics=True (#6389)
- [ ] revisit memory limit limits for default local cluster (https://github.com/dask/distributed/issues/3956)
- [ ] investigate a way to monitor and report on GIL contention or thread lock waits (#6391)
- [ ] find more examples to make profile investigations from for the future (#6392)
- [ ] why didn't the profile tab show up for me??

**Comment by mrocklin** [comment]
cc @dankerrigan this may interest you?

**Comment by TomAugspurger** [comment]
Purely for getting better numbers, I suspect the lowest hanging-fruit is using the the threaded scheduler or processes=False in https://github.com/xdssio/big_data_benchmarks/blob/master/notebooks/dask.ipynb. I'd guess most of these workload releases the GIL.

But there's likely things to improve regardless of the scheduler.

**Comment by kkraus14** [comment]
Is it worth bringing up that for other distributed frameworks like vaex that the notebooks aren't converting the results to a local numpy array / Pandas dataframe yet for Dask they're calling `.compute()` on every method as opposed to calling `wait` + `persist`?

It's also comparing reading from disk each time with vaex using uncompressed hdf5 (so it can just be memmapped), versus SNAPPY compressed Parquet files for Dask.

**Comment by mrocklin** [comment]
Yeah, it may be that the benchmark is unfair.  Personally I don't care that
much about the bad press (there is a blogpost like this every few weeks).
I'm much more interested in using the notebooks that they have to help us
understand how people trip up, and how we can make things more robustly
performant.

**Comment by martindurant** [comment]
Early report on findings. This is with latest versions from conda-forge.

Notes: 
- the dataset is 25.2GB in 1174 files (22MB per file), no metadata of common_metadata file
- 18 columns, so each column of each file is a small amount of data
- the first partition expands to 360MB (137MB not including strings) in memory from 24.5MB file
- the index is a range, i.e., generated rather than loaded

Some findings
- **dd.read_parquet still performs gather_statistics**, apparently, since gather_statistics=False returns much quicker. This is disappointing, since there is no useful division information. Although it's not possible to get just some stats from the pyarrow metadata, the code should bail as soon as the second file, since we know by then that the statistics are not useful.
- **len(df) loads all the data**; we know about this one. Selecting any column makes the process much faster, but users don't know this, and it ought not to be necessary. Indeed, `len` should bypass loading at all, the count is known from parquet metadata alone. The blog uses `len(df.vendor_id)`, which is a string col (length-one, I think), and, if you do have to pick one, this would be faster with `df.passenger_count`, the only integer field.
- **len(df.index) loads all the data**; this doesn't seem to trigger the column select optimisation, perhaps there is no index column in the data. It also shouldn't need to load any data at all, it's just generated
- **large number of files**; although the best practices mentions repartitioning, we don't warn even when we know there are lots of files, or when we realise that each file is somewhat small. I don't know how some more information could be more easily provided, and whether the load itself might get X files in a single task (i.e., fused reading, which would work very nicely with async filesystems)
- **large complex graphs from chained syntax**; something like the following
```
expr_filter = (data.pickup_longitude > long_min)  & (data.pickup_longitude < long_max) & \
                  (data.pickup_latitude > lat_min)    & (data.pickup_latitude < lat_max) & \
                  (data.dropoff_longitude > long_min) & (data.dropoff_longitude < long_max) & \
                   (data.dropoff_latitude > lat_min)   & (data.dropoff_latitude < lat_max)
data2 = data[expr_filter]
```
 results in 24654 tasks, but you could do the same with `map_partitions` to get 2348. This is true whether doing long arithmetic or complicated filtering like this. These are the cause of the majority of the apparent slowness in the blog.
- an expression like the above will, I think will do a **load each file for each column selection**, where you might hope that a single load of all of the relevant columns, and only those, would load
- **workers die**; I haven't yet investigated, but I think this might be a recurrence of the memory not being released on multiple alloc/free of pandas dataframes. Or perhaps spilling wasn't working.  I'm surprised that `Client()` has a hard memory limit and doesn't allow python to approach a real MemoryError (which would at least be more informative). Can we check the size of (process memory - sum(in-memory keys)) to see if we are leaking, and perhaps this offers a point where a workers in-memory keys can be drained to allow a restart.

**Comment by TomAugspurger** [comment]
> The blog uses len(df.vendor_id),

So this probably hits the HLG optimization that rewrites `read_parquet(...)['col'])` as `read_parquet(..., usecols=['col'])`, which is good. But I'd hoped that The blog uses `DataFrame.__len__` would also get this: https://github.com/dask/dask/blob/4d7e674189ed2473ea2dcc2ddf3536e519bd1da5/dask/dataframe/core.py#L3487-L3493. I suspect that `.iloc[:, 0]` doesn't trigger the same optimization.

> the count is known from parquet metadata alone.

Is that always available, or does the dataset need to be written specially? That seems like a relatively straightforward optimization that we could put it.

**Comment by mrocklin** [comment]
Whoa, nice report @martindurant !

> dd.read_parquet still performs gather_statistics

Fully agreed on the "bail early" if nothing is sorted fix.

> len(df) loads all the data
> len(df.index)

It sounds like maybe `len(df)` should become `len(df.index)` and that we should try to see if we can extend the parquet optimization to take the index into account.

> large number of files

No thoughts on this, other than docs and dashboards

> large complex graphs from chained syntax

I'm surprised that the blockwise fusion optimization didn't catch this

**Comment by kkraus14** [comment]
> > large number of files
> 
> No thoughts on this, other than docs and dashboards

Do we directly use pyarrow for parquet reading or do we go through Pandas? Something we've seen from testing is if the files are relatively small that if you can pass a chunk of them at once to PyArrow there's likely speedup opportunities versus reading them individually. In addition to that, it helps to avoid downstream problems from having a large number of small partitions.

Maybe we could do something where if we have metadata we could determine that we actually want say 4 parquet files in this partition as opposed to a separate partition per parquet file.

**Comment by mrocklin** [comment]
> Maybe we could do something where if we have metadata we could determine that we actually want say 4 parquet files in this partition as opposed to a separate partition per parquet file.

I think that @rjzamora actually has already added this.  I think that there is a keyword that you can use to specify an ideal chunksize.  

I think that what you're proposing is that we start bundling partitions up automatically.

**Comment by rjzamora** [comment]
> I think that @rjzamora actually has already added this. I think that there is a keyword that you can use to specify an ideal chunksize.

We do have the `chunksize` argument, but this approach is quite slow.  I'm planning to improve the peformance in the near future since working in the new `pyarrow.datasets` API will likely require a minor refactor anyway.  Note that the current `chunksize` approach is so slow that I completely avoided the use of `read_parquet` in [nvtabular](https://github.com/NVIDIA/NVTabular/blob/5271e0a39e666602d2b4ffc8b7f08413ccb76332/nvtabular/dask/io.py#L307) (where we need exactly this behavior).

**Comment by mrocklin** [comment]
What did you do instead?

**Comment by rjzamora** [comment]
> What did you do instead?

Since we are not interested in detecting an index, filtering, or calculating divisions, we just avoid the statistics-processing step.  Instead, we use the first row-group in the dataset to estimate the size of all row groups (obviously a big assumption, but tends to work well) and then use the available parquet metadata to compile the list of "pieces" that will ultimately be read in as partitions.  A piece looks something like: `(<path>, <list-of-row-group-indices>)`.

Skipping the statistics processing step seems to reduce the "planning" stage of the read by **tens** of seconds for large datasets.  However, we also get a performance boost on the cudf backend by reading in a list of many row-groups (at once) for each partition.  The current `read_parquet` logic doesn't allow this, because it will ask the engine to read a single row-group at a time and then concatenates them together.

**Comment by mrocklin** [comment]
Are there changes we could make to dask.dataframe.read_parquet that would
make it attractive enough to reuse?  Short-circuiting reading metadata if
the dataset isn't sorted?  Automatic grouping of many small partitions if
there are lots of partitions?  (using the first ten or so to estimate
size)

**Comment by rjzamora** [comment]
> Are there changes we could make to dask.dataframe.read_parquet that would
make it attractive enough to reuse?  Short-circuiting reading metadata if
the dataset isn't sorted?  Automatic grouping of many small partitions if
there are lots of partitions?  (using the first ten or so to estimate
size)

Yes - I absolutely do plan to improve `dask.dataframe.read_parquet` and avoid maintaining an alternative version of something similar.  I think the necessary changes are generally: (1) Allow row-group aggregation with `gather_statistics=False`, and (2) allow the engine to read multiple row-groups at once.  I would like to

**Comment by martindurant** [comment]
> Is that always available, or does the dataset need to be written specially? 

Each parquet file says how many rows it has in the metadata (and how many rows each constituent row-group has, where that might be important); if there is a global metadata, it says how many rows there are over all.

> I suspect that df.iloc[:, 0] doesn't trigger the same optimization.

Is this identical to `df[df.columns[0]]`?

> I'm surprised that the blockwise fusion optimization didn't catch this

Actually, you are right, that was the number of tasks pre-optimize. I'll have to check back to see how many tasks actually ran.

> Short-circuiting reading metadata if the dataset isn't sorted?  Automatic grouping of many small partitions if there are lots of partitions?

Both are useful and doable, the former being the quick win that will affect people's experience when doing interactive work. I'm not sure why statistics were being collated at all for this data-set, I thought it would be false by default when there is no global metadata.

**Comment by martindurant** [comment]
I should also add another known shortcoming: we consider all partitions, even when there is a filter that we could have known was not satisfiable in some partitions, according to the statistics metadata. We've discussed this before too.

**Comment by martindurant** [comment]
Note that the standard mix that `Client()` got for the benchmark was four processes, four threads each. The majority of the time in len(filtered thing) is in the fused func getitem-read-parquet-len-chunk and len(chunk) is a separate fast task (one per input partition) ; the profile tab is not working for some reason.

**Comment by martindurant** [comment]
When using all processes, the first filter example finishes in 1m51; when using all threads in-proc, it takes 11m33. This is despite much of the work being IO (not async!) and pandas.
So: is GIL contention something we should be attempting to measure and report? (like https://github.com/chrisjbillington/gil_load )

**Comment by martindurant** [comment]
Furthermore, I can confirm that filtering by the complex expression does cause all columns to be loaded, whether doing len on a single column or the whole dataframe.

**Comment by TomAugspurger** [comment]
>>    I suspect that df.iloc[:, 0] doesn't trigger the same optimization.

> Is this identical to df[df.columns[0]]?

Not entirely (duplicate column labels perhaps), but it should be close enough for `__len__`. It should trigger the optimization, or we can update the optimization to handle `iloc`.

> I can confirm that filtering by the complex expression does cause all columns to be loaded

Do you mean the expression like

```python
expr_filter = (data.pickup_longitude > long_min & ...)
data2 = data[expr_filter]
```

Isn't the user requesting that all the data be loaded there?

> When using all processes, the first filter example finishes in 1m51; when using all threads in-proc, it takes 11m33.

Can you share a performance report of this? I'd be interested in seeing the communication pattern.

**Comment by martindurant** [comment]
> Do you mean the expression like
```
expr_filter = (data.pickup_longitude > long_min & ...)
data2 = data[expr_filter]
```

> Isn't the user requesting that all the data be loaded there?

No, I meant even if you then do `len(data2.column)` (which should only need the two filter columns and one column to measure the len, which would ideally also be one of the filter columns)

Interestingly, the majority of time taken is in `pyarrow.lib.table_to_blocks`, which I don't suppose there's much we can do about (although, again, a pyarrow table knows its length without conversion to pandas - if filtering could be pushed down to arrow - but can't do any processing more interesting than that)

Profile for one partition run in sync
```
        21636 function calls (19600 primitive calls) in 1.172 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.499    0.499    0.499    0.499 {pyarrow.lib.table_to_blocks}
        1    0.247    0.247    0.247    0.247 {method 'read_all' of 'pyarrow._parquet.ParquetReader' objects}
        2    0.108    0.054    0.108    0.054 {pandas._libs.algos.take_2d_axis0_float64_float64}
    119/6    0.104    0.001    1.165    0.194 core.py:86(_execute_task)
        2    0.041    0.020    0.041    0.020 {pandas._libs.algos.take_2d_axis0_object_object}
       28    0.038    0.001    0.038    0.001 {built-in method numpy.empty}
        1    0.025    0.025    0.025    0.025 {pandas._libs.algos.take_2d_axis1_object_object}
        1    0.024    0.024    0.024    0.024 {pandas._libs.algos.take_2d_axis1_float64_float64}
        1    0.015    0.015    0.864    0.864 arrow.py:478(read_partition)
        2    0.013    0.006    0.013    0.006 {pandas._libs.algos.take_2d_axis1_int64_int64}
        1    0.008    0.008    0.008    0.008 {pandas._libs.algos.take_2d_axis0_int64_int64}
        8    0.006    0.001    0.007    0.001 array_ops.py:202(comparison_op)
        4    0.005    0.001    0.005    0.001 {method 'take' of 'numpy.ndarray' objects}
       16    0.005    0.000    0.005    0.000 {method 'astype' of 'numpy.ndarray' objects}
```

Interestingly, fastparquet beats pyarrow for this particular calculation (just: 1.08s versus 1.15s)

**Comment by TomAugspurger** [comment]
The table benchmark table: https://h2oai.github.io/db-benchmark/

**Comment by martindurant** [comment]
Actions summary:
- make len(df) be len(df.index), and that this actually triggers the existing columns optimization for parquet
- specifically for len(df) from parquet, use metadata nrows value rather than loading
- combine column selections and also pass down to parquet (and csv or others!)
- gather_statistics in read_parquet: revisit when this is triggered at all, and quit early if failing, preventing the load of metadata even if gather_statistics=True
- revisit memory limit limits for default local cluster
- investigate a way to monitor and report on GIL contention or thread lock waits.
- find more examples to make profile investigations from for the future
- why didn't the profile tab show up for me??

**Comment by owenlamont** [comment]
Hi Dask team. I was looking today see if you had any response to that benchmark and happy to see you’re already on it. Was there any follow up on the apparent worker stability issues mentioned in it? It’s assumed to be a Pandas memory leak?

**Comment by TomAugspurger** [comment]
@martindurant did you have any issues with workers crashing?

**Comment by martindurant** [comment]
I did not run many of the tests, I didn't see this.
@owenlamont , I was voicing my guess, I don't have proof. However, I did mention in my summary that the default local client probably shouldn't be killing workers, that's an open item.

**Comment by martindurant** [comment]
@TomAugspurger (or @jcrist , @mrocklin ), do we have any existing code around to check for the pandas leak problem that used to be a real issue?

**Comment by TomAugspurger** [comment]
I don't have anything handy.

**Comment by mrocklin** [comment]
I've taken @martindurant 's list of action items and placed it as a checkbox list in the opening comment

If people have time to go through that list and see if there are still things that we should resolve before meeting tomorrow that would be helpful.

**Comment by mrocklin** [comment]
I think that @martindurant is planning to rerun the example later this week or next and report back on changed performance.

**Comment by martindurant** [comment]
I will start a new issue with latest findings

**Comment by martindurant** [comment]
Closing this issue now, since the individual findings became their own issues, and the exercise was repeated (see linked issues)
